name: deploy
on:
  push:
    branches:
      - main
jobs:
  check-version:
    name: Check package version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check-pypi-version.outputs.local_version }}
      increased: ${{ steps.check-pypi-version.outputs.local_version_is_higher }}
    steps:
      - uses: actions/checkout@v3

      - name: Check PyPI version
        uses: maybe-hello-world/pyproject-check-version@v1
  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/c64os-util
    permissions:
      id-token: write
    needs: check-version
    if: ${{ needs.check-version.increased == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Generate tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ needs.check-version.version }}
