name: deploy
on:
  push:
    branches:
      - main
jobs:
  check-version:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check PyPI version
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://pypi.org/pypi/c64os-util/json

      - name: Set remote version
        run: echo "REMOTE=${{ fromJSON(env.fetch-api-data).info.version }}" >> "$GITHUB_OUTPUT"

      - name: Set local version
        run: echo "LOCAL=$(poetry version -s)" >> "$GITHUB_OUTPUT"
  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/c64os-util
    permissions:
      id-token: write
    needs: check-version
    if: ${{ needs.check-version.LOCAL != needs.check-version.REMOTE }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build
