name: deploy
on:
  push:
    branches:
      - main
jobs:
  check-version:
    name: Check package version
    runs-on: ubuntu-latest
    outputs:
      remote: ${{ fromJSON(env.fetch-api-data).info.version }}
      local: ${{ env.pkg_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check PyPI version
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://pypi.org/pypi/c64os-util/json

      - name: Check package version
        run: echo "pkg_version=$(poetry version -s)" >> "$GITHUB_ENV"
  print-dbg:
    name: Print statements for debug
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - run: echo ${{ needs.check-version.remote }}
      - run: echo ${{ needs.check-version.local }}
  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/c64os-util
    permissions:
      id-token: write
    needs: check-version
    if: ${{ needs.check-version.local != needs.check-version.remote }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build
