name: deploy
on:
  push:
    branches:
      - main
jobs:
  check-version:
    name: Check package version
    runs-on: ubuntu-latest
    outputs:
      remote: ${{ fromJSON(env.fetch-api-data).info.version }}
      local: ${{ steps.check-local.outputs.pkg_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check PyPI version
        id: check-remote
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://pypi.org/pypi/c64-os/json

      - name: Check package version
        id: check-local
        run: pkg_version=$(poetry version -s)
  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/c64os-util
    permissions:
      id-token: write
    needs: check-version
    if: ${{ needs.check-version.local != needs.check-version.remote }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Generate tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ needs.check-version.local }}
